package com.minecraftbridge;

import net.fabricmc.loader.api.FabricLoader;
import net.fabricmc.loader.api.entrypoint.PreLaunchEntrypoint;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

// preLaunch runs before any ModInitializer (including Geyser's), so our Geyser
// config write wins the race when no config exists yet. Must not touch Minecraft classes.
public class BedrockBridgePreLaunch implements PreLaunchEntrypoint {

	@Override
	public void onPreLaunch() {
		Path configPath = FabricLoader.getInstance().getConfigDir()
				.resolve("Geyser-Fabric").resolve("config.yml");
		if (Files.exists(configPath)) {
			BedrockBridge.LOGGER.info("Config Geyser ya existe en {}, no se sobreescribe.", configPath);
			return;
		}
		try {
			Files.createDirectories(configPath.getParent());
			Files.writeString(configPath, DEFAULT_GEYSER_CONFIG);
			BedrockBridge.LOGGER.info("Config Geyser por defecto escrito en {} (auth-type=floodgate).", configPath);
		} catch (IOException e) {
			BedrockBridge.LOGGER.error("No se pudo escribir el config de Geyser en {}", configPath, e);
		}
	}

	private static final String DEFAULT_GEYSER_CONFIG = """
			# Generated by BedrockBridge on first run. Edit freely — won't be overwritten.
			bedrock:
			  address: 0.0.0.0
			  port: 19132
			  clone-remote-port: false
			java:
			  auth-type: floodgate
			motd:
			  primary-motd: BedrockBridge
			  secondary-motd: Compartiendo con Bedrock
			  passthrough-motd: true
			  passthrough-player-counts: true
			gameplay:
			  show-coordinates: true
			default-locale: system
			log-player-ip-addresses: true
			pending-authentication-timeout: 120
			notify-on-new-bedrock-update: true
			advanced:
			  floodgate-key-file: key.pem
			enable-metrics: true
			debug-mode: false
			config-version: 7
			""";
}
